### ISSUE TITLE
Can't install plugin by env GERRIT_INIT_ARGS

### ISSUE THREAD

**Issue by 9Cube-dpustula** [openfrontier/docker-gerrit#114]
Hi im trying to install plugin as you describe in [readme](https://github.com/openfrontier/docker-gerrit#install-plugins-on-start-up), but when im run container i stuck on this:
```
gerrit_1      |
gerrit_1      | /gerrit-entrypoint.sh: ignoring /docker-entrypoint-init.d/*
gerrit_1      |
gerrit_1      | Waiting for database connection postgres:5432 ...
gerrit_1      | Upgrading gerrit...
gerrit_1      | fatal: No argument is allowed: '--install-plugin=download-commands'
```

My gerrit service in docker-compose : 

```yaml
version: '3'

services:
  gerrit:
    image: openfrontier/gerrit
    ports:
      - "29418:29418"
      - "8080:8080"
    links:
      - postgres
      - ldap
    depends_on:
      - postgres
      - ldap
    environment:
    - WEBURL=http://localhost:8080
    - DATABASE_TYPE=postgresql
    - DATABASE_HOSTNAME=postgres
    - DATABASE_PORT=5432
    - DATABASE_DATABASE=reviewdb
    - DATABASE_USERNAME=gerrit
    - DATABASE_PASSWORD=secret
    - AUTH_TYPE=LDAP
    - LDAP_SERVER=ldap://ldap
    - LDAP_USERNAME=cn=admin,dc=example,dc=org
    - LDAP_PASSWORD=secret
    - LDAP_ACCOUNTBASE=dc=example,dc=org
    - LDAP_ACCOUNTPATTERN=(&(objectClass=person)(uid=$${username}))
    - LDAP_ACCOUNTFULLNAME=displayName
    - LDAP_ACCOUNTEMAILADDRESS=mail
    - DOWNLOAD_SCHEMES=http ssh
    - GERRIT_INIT_ARGS='--install-plugin=download-commands'
```
