### ISSUE TITLE
Request: Kubernetes objects templates

### ISSUE THREAD

**Issue by Novitoll** [openfrontier/docker-gerrit#86]
Please add the basic YAML templates for Deployment, Service, Secrets, PersistentVolume objects in Kubernetes (>= 1.8.2)  for Gerrit.

Also Gerrit + Jenkins + SonarQube integration in k8s will be brilliant. (Helm packaging is optional)

**Comment by thinkernel** [comment]
I'm thinking of this idea, too.
However, I've been struggling with the k8s environments for a while.

**Comment by Novitoll** [comment]
OK, I can do it actually but later. The Deployment part might look like

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gerrit
  labels:
    app: gerrit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gerrit
  template:
    metadata:
      labels:
        app: gerrit
    spec:
      containers:
      - name: gerrit
        image: openfrontier/gerrit:latest
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: env-config
          - secretRef:
              name: secrets
        ports:
        - name: gerrit-web
          containerPort:
            valueFrom:
              configMapKeyRef:
                name: value-config
                key: web_port
        - name: gerrit-ssh-agent
          containerPort:
            valueFrom:
              configMapKeyRef:
                name: value-config
                key: ssh_agent_port
```
