### ISSUE TITLE
Gerrit docker volume permissions issue

### ISSUE THREAD

**Issue by mgrzechocinski** [openfrontier/docker-gerrit#99]
Hi.

I'm struggling with strange Gerrit issues after upgrading from 2.14.x (do not remember which exactly) to 2.15.2. I started a discussion on Gerrit mailing list [here](https://groups.google.com/forum/#!topic/repo-discuss/vKs15HtImkU) but I was led to the point where there's a strange behaviour of Gerrit running in a container made out of this image.

When I run this image through docker-compose and log into the container by `docker exec -u gerrit2 -it gerrit-container` I'm able to browse my gerrit review site. What looks strange for me is the permissions in `var/gerrit/review_site/git/training.git/refs/changes`:

```
bash-4.4$ ls -al
drwxr-xr-x    3 gerrit2  gerrit2        102 Jul 27 07:37 88
drwxr-xr-x    4 gerrit2  root           136 Jul 27 08:46 90
drwxr-xr-x    4 gerrit2  root           136 Jul 27 08:58 93
drwxr-xr-x    4 root  root              136 Jul 27 09:24 94
drwxr-xr-x    3 gerrit2  gerrit2        102 Jul 27 09:33 95
drwxr-xr-x    3 gerrit2  gerrit2        102 Jul 27 11:46 97
drwxr-xr-x    3 gerrit2  gerrit2        102 Jul 27 13:39 98
drwxr-xr-x    4 gerrit2  root           136 Jul 27 14:35 99
```
How is it possible that some folders are owned by gerrit2, some by root and same with group it. This state of my volume causes many strange errors when publishing changes or trying to merge them.

Frankly, I have no idea why this happens. I run Docker on Mac. My docker-compose looks like this:

```
version: '3'

services:
  nginx:
    container_name: nginx-container
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ~/Docker/infra_mobiledev/nginx/conf/:/etc/nginx/conf.d/
      - ~/Docker/infra_mobiledev/nginx/fancyindex_theme_1/:/usr/share/nginx/fancyindex_theme:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - gerrit
  gerrit:
    container_name: gerrit-container
    image: openfrontier/gerrit:latest
    volumes:
      - ~/Docker/infra_mobiledev/gerrit_home:/var/gerrit/review_site
    environment:
    - MIGRATE_TO_NOTEDB_OFFLINE=1
    - AUTH_TYPE=HTTP
    - WEBURL=https://localhost/gerrit/
    - AUTH_EMAIL_FORMAT={0}@example.org
    - HTTPD_LISTENURL=proxy-https://gerrit:8080/gerrit/
    - GERRIT_INIT_ARGS=--install-plugin=download-commands
    - GERRIT_START_ACTION=daemon
    ports:
      - "29418:29418"
```
